pub mod data;
pub mod toString;

#[test]
fn test_empty() {
    assert_eq!(
        toString::to_string(
            data::Code {
                export_definition_list: vec![],
                statement_list: vec![]
            },
            data::CodeType::JavaScript
        ),
        "/* eslint-disable */\n/* generated by js-ts-code-generator. Do not edit! */\n\n"
    );
}
